### ISSUE TITLE
[BUG] - Overlay don't want to start

### ISSUE THREAD

**Issue by ezemania2** [DorielRivalet/mhfz-overlay#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/DorielRivalet/mhfz-overlay/assets/81659486/50a2c368-c7cf-46db-94d2-e069a4d30278)
he stay in the task manager but no overlay

### How often does the bug occur?

Sometimes

### What operating system are you using?

Windows 10 21H2

### What version of the program are you using?

Latest version

### What version of the game are you using?

High-Grade Edition

### Quest ID

no quest

**Comment by DorielRivalet** [comment]
See if reinstalling fixes the issue.

**Comment by ezemania2** [comment]
OK I'll when I'll be wake up

**Comment by ezemania2** [comment]
same :/

**Comment by DorielRivalet** [comment]
Go to the folder where the overlay exe is, go to app-0.24.1 folder, go to logs folder, then show me what logs.log says.

**Comment by ezemania2** [comment]
I checked the end and... he don't want 'cause CE was opened for another game...

**Comment by DorielRivalet** [comment]
Is the issue resolved?

You cannot use the overlay while CE is running.

**Comment by ezemania2** [comment]
yes its resolved

**Comment by DorielRivalet** [comment]
If you encounter any further issues or have any questions, please don't hesitate to reach out.

**Comment by ezemania2** [comment]
Sure thx for help !
