### ISSUE TITLE
[BUG]- Setup crash

### ISSUE THREAD

**Issue by Raditz1101** [DorielRivalet/mhfz-overlay#121]
I was trying to boot the Setup file and get these 2 errors, I have the dll file in its proper place so idk what the issue is

![Pain](https://github.com/DorielRivalet/mhfz-overlay/assets/138386305/3dac8a81-f2b4-4582-97d6-c5a8f361179d)
![PainElectricBoogaloo](https://github.com/DorielRivalet/mhfz-overlay/assets/138386305/3f813ab8-e67c-45f1-ae7f-f15dec2588d1)

**Comment by DorielRivalet** [comment]
What does Squirrel.log show?

**Comment by Raditz1101** [comment]
> What does Squirrel.log show?

Well I went looking for the file and it apparently doesn't exist, SquirrelClowdTemp just isn't a thing on my laptop as far as I can tell

**Comment by Raditz1101** [comment]
> What does Squirrel.log show?

Im on windows 7 btw idk if that helps

**Comment by DorielRivalet** [comment]
This seems related to #84. I'm closing this issue and posting updates there when support for Windows 7 is added.
