### ISSUE TITLE
[BUG] - Crashing every few quests

### ISSUE THREAD

**Issue by the-color-cyan** [DorielRivalet/mhfz-overlay#123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Every maybe 3-5 quests the overlay seems to just close itself quietly (seems like this happens during quest loading but I'll have to be paying more attention when it happens). I've checked the install folder in AppData and don't see any log files or a log folder, so if there's any more info I can provide just let me know.

### How often does the bug occur?

Always

### What operating system are you using?

Windows 10 21H2

### What version of the program are you using?

Latest version

### What version of the game are you using?

High-Grade Edition

### Quest ID

0

**Comment by DorielRivalet** [comment]
Can you check if this folder exists? `C:\Users\NAME\AppData\Local\MHFZ_Overlay\app-0.24.1\logs`

**Comment by the-color-cyan** [comment]
It does! I'm not seeing anything in particular around where the crashes are happening though. The only fatal errors I see are from times when I've accidentally launched a second instance of the application. I'll attach the logfile in case there's anything useful.
> 
[logs.log](https://github.com/DorielRivalet/mhfz-overlay/files/11997148/logs.log)

**Comment by DorielRivalet** [comment]
Hi, I recently checked the logs file. I can't seem to find the cause of the issue, however I noticed that it might be an unhandled exception, meaning that such errors wouldn't have been logged. I updated some code to handle such cases.

The overlay is pending an update release at the moment, once it's ready I'll give an update notice.

**Comment by the-color-cyan** [comment]
Perfect, thanks! I'll be sure to update it and test it when it's out.

**Comment by DorielRivalet** [comment]
The update is out. Look out for "Unhandled exception" in the logs file if the issue still occurs.
