### ISSUE TITLE
[BUG] - The overlay gives me this error what can I do

### ISSUE THREAD

**Issue by ShiroDou365** [DorielRivalet/mhfz-overlay#142]
![Uploading image.png…]()
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

every time I run the overlay it asks me to update, I update but it gives an error and doesn't let me use the overlay

### How often does the bug occur?

Rarely

### What operating system are you using?

Windows 10 21H2

### What version of the program are you using?

Latest version

### What version of the game are you using?

High-Grade Edition, Non High-Grade Edition

### Quest ID

64123

**Comment by DorielRivalet** [comment]
Can you re-send the image? Also send the logs file found in `%localappdata%/MHFZ_Overlay/app-0.27.3/logs`.
