### ISSUE TITLE
[BUG] - Overlay crash after quest

### ISSUE THREAD

**Issue by Ninejar** [DorielRivalet/mhfz-overlay#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Whenever I finish a quest, I get a fatal error which force closes the overlay. The error occurs right as I get to the reward screen, and it happens in every quest I've tried - HR, HR5, G-Rank (the provided quest ID is a GR quest) and Zenith. From what I can tell from the error message, as well as when the crash happens, it has something to do with the quest logging, but idk what.
The same thing happens both with and without high-grade edition.

[non_high-grade.log](https://github.com/DorielRivalet/mhfz-overlay/files/12243692/non_high-grade.log)
[high-grade.log](https://github.com/DorielRivalet/mhfz-overlay/files/12243693/high-grade.log)

### How often does the bug occur?

Always

### What operating system are you using?

Windows 10 22H2

### What version of the program are you using?

Latest version

### What version of the game are you using?

Non High-Grade Edition

### Quest ID

23255

**Comment by DorielRivalet** [comment]
I identified the cause of the issue which seems to be related to how the user system handles decimals (e.g. 0,0 instead of 0.0). I'll see if I can release a fix soon.

**Comment by DorielRivalet** [comment]
I released an update. I can re-open the issue if its still present.

**Comment by Ninejar** [comment]
The update fixed it, yea. Thanks :)
