### ISSUE TITLE
[BUG] - Overlay suddenly getting weird HP or Status values on 9999 Fatalis after switching zones.

### ISSUE THREAD

**Issue by Nerscylia** [DorielRivalet/mhfz-overlay#177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

At long fights against LVL 9999 Fatalis. if you change zone (you can go to the camp) sometimes fatalis HP goes from 533K to 126Millions or it starts changing a lot, sometimes not even displaying remaining HP.

Here I put a couple screenshots, one with the correct HP, and other when it started to bug.

Bugged HP

![image](https://github.com/DorielRivalet/mhfz-overlay/assets/143104576/b37f30aa-a852-4263-9ea0-7c1fd3c21cad)

Normal HP.

![image](https://github.com/DorielRivalet/mhfz-overlay/assets/143104576/9fc20290-98fc-43a7-b3b3-dbf7c60ae2b9)

### How often does the bug occur?

Sometimes

### What operating system are you using?

Windows 10 21H2

### What version of the program are you using?

Latest version

### What version of the game are you using?

High-Grade Edition

### Quest ID

23596

**Comment by DorielRivalet** [comment]
If you set the maximum defrate threshold to 0.999 does the issue still occur? Setting on here 
![image](https://github.com/DorielRivalet/mhfz-overlay/assets/100863878/f4f721cc-4d29-4283-b840-f6a1560d1996)
