### ISSUE TITLE
Overlay will not even load

### ISSUE THREAD

**Issue by PBPStudios** [DorielRivalet/mhfz-overlay#271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Downloaded the MHFZ_OverlaySetup.exe File
Ran it as administrator 
Setup was completed
Launched MHFZ, Logged In, and entered Mezaporta
Launched the MHFZ_Overlay
Asks me if "I wish to run the application?" Selected "Yes"
Nothing Happens after. No overlay or records of the application even starting were present.
Assumed something wasn't installed properly, Checked The AppData/Local Folders. (Found the file directory)
Looked for a possible crash report (None were available)
Decided to uninstall and try a previous version of the overlay.
Same results as previous.

### How often does the bug occur?

Always

### What version of the program are you using?

I'm using...
The MHFZ Overlay (0.33.0)
.NET Desktop Runtime 6.0 x64 (6.0.26)
.NET Desktop Runtime 6.0 x86 (6.0.26)
MHFZ Launcher 2.016 

I hope this helps or you can find out what I've done wrong.. thanks!

**Comment by DorielRivalet** [comment]
Do you get a black screen when loading the overlay? See #61 for similar issue.
