### ISSUE TITLE
[BUG] - System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.

### ISSUE THREAD

**Issue by Marigoldss** [DorielRivalet/mhfz-overlay#364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Looking at the Log, it looks like I'm running out of memory, but I'm pretty sure my computer specs are sufficient.
core i7 10700kf rtx4070ti 32gbmemory

I've been using 0.37.0 until now and all of a sudden today I'm getting this error (2024.07.20)
The same problem occurs in the latest version 0.40.0 and other ver.
I also searched google about Crashlog but could not solve it for me.
The moment i launch Overlay, it obviously runs slower than before.
WinUpdate may be the cause, but the problem was happening even before the update.

And my Overlay folder is C:\Users\Name\AppData\Local\MHFZ_Overlay\current
and packages,reference_schema.json,update.exe only.
not app-xyz,logs.
But Logs are available when the overlay crashes

[overlay crashlog.txt](https://github.com/user-attachments/files/16321732/overlay.crashlog.txt)

### How often does the bug occur?

Always

### What version of the program are you using?

Latest version
0.37.0 and 1
0.38.0
0.39.0

**Comment by DorielRivalet** [comment]
1. Go to game folder, then `database` folder, then delete `previous-version.txt` and `MHFZ_Overlay.sqlite` (or move to any other folder).
2. Go to `%LocalAppData%\MHFZ_Overlay` then delete `reference_schema.json`.
3. Uninstall overlay.
4. Install latest overlay version (v0.40).

**Comment by Marigoldss** [comment]
After this problem I went to v0.36.1 and it was working, so I was using that, but I tried the method you described and it started up fine on v0.40!
Thank you so much.
