### ISSUE TITLE
[BUG] - Can't seem to get the Overlay working?

### ISSUE THREAD

**Issue by Goji-Moji** [DorielRivalet/mhfz-overlay#369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've tried running the setup and reinstalling many times now. When I run the overlay (in Mezeporta and as Administrator of course) I get the messages 
<img width="316" alt="MHFZ Overlay message 1" src="https://github.com/user-attachments/assets/fc8be05d-bcb0-42ab-a2a8-92adaa15491c">
<img width="311" alt="MHFZ Overlay message 2" src="https://github.com/user-attachments/assets/589b73bc-e888-491d-8396-af07055f54ef">

I assume it needs time run in the background, but it seems like it's not doing anything?

<img width="504" alt="MHFZ Overlay task manager" src="https://github.com/user-attachments/assets/2db8707a-4931-42dc-a332-120dbf2d76d9">

Shift+F1 never does anything, nor any other command. Not sure why it needs to update, since I started the install from the latest version, but it never seems to just become active or usable. The link it opens doesn't seem to do anything useful in particular, I already downloaded the version it's leading me to and the page itself offers no instructions. Not really sure what to do here. How long am I supposed to wait for it to do what it's supposed to do? Changing the resolution or switching between windowed and fullscreen mode or restarting the app between switches also doesn't do anything.

### How often does the bug occur?

Always

### What version of the program are you using?

Latest version

**Comment by Ashura-Yang** [comment]
Hey dude it happens to me as well with the version 0.41.0 can u maybe tell me what u did to fix it please??? ;-;
