### ISSUE TITLE
[BUG] - <Ferias not usable>

### ISSUE THREAD

**Issue by ezemania2** [DorielRivalet/mhfz-overlay#37]
### What happened?

![image](https://user-images.githubusercontent.com/81659486/206887452-7b7627b6-57ab-4bf6-90bf-2bb02558f894.png)
![image](https://user-images.githubusercontent.com/81659486/206887460-647317f5-db50-4b4c-bb19-a4f89d3fbd0c.png)
with that version of Ferias
![image](https://user-images.githubusercontent.com/81659486/206887521-f7734383-2199-4923-9c46-e6b1c64ab81b.png)

### What version of the program are you using?

Latest version

### What version of the game are you using?

High-Grade Edition

**Comment by DorielRivalet** [comment]
Thank you for the bug report. Now fixed in version [0.18.1](https://github.com/DorielRivalet/mhfz-overlay/releases/tag/v0.18.1)
