### ISSUE TITLE
[BUG] - Nonfunctioning after launch.

### ISSUE THREAD

**Issue by RorschachGiant** [DorielRivalet/mhfz-overlay#47]
### What happened?

I cant pinpoint what causes it, but immediately after launching the overlay after having loaded into Mezeporta, I can no longer use the shortcuts to bring up the menu, restart, or close the overlay. The elements that do load are static, even when loading into a quest. I have tried reinstalling the overlay and force closing it and reloading it. I can occasionally retain function momentarily but usually after a little bit after restarting it seems to freeze/stop responding. 

I mainly just want to retain the functionality of the database that is convienient.

### What version of the program are you using?

Latest version

### What version of the game are you using?

High-Grade Edition

**Comment by VictorChan7** [comment]
Can you add the ability to view all reward items for ongoing missions?

**Comment by DorielRivalet** [comment]
> ### What happened?
> I cant pinpoint what causes it, but immediately after launching the overlay after having loaded into Mezeporta, I can no longer use the shortcuts to bring up the menu, restart, or close the overlay. The elements that do load are static, even when loading into a quest. I have tried reinstalling the overlay and force closing it and reloading it. I can occasionally retain function momentarily but usually after a little bit after restarting it seems to freeze/stop responding.
> 
> I mainly just want to retain the functionality of the database that is convienient.
> 
> ### What version of the program are you using?
> Latest version
> 
> ### What version of the game are you using?
> High-Grade Edition

Does the issue still occur in version 0.21.0?

**Comment by RorschachGiant** [comment]
The specific issue in question so far doesn't seem to persist with the newest update. However I have noticed decreased performance on my computer with the config open, and even the overlay crashing while I had the config open, if I was for instance looking at armor skills while scrolling through armors with my controller or alt tab to make notes in a document of mine on my second monitor.
