### ISSUE TITLE
How did uploaďmy run on your overlay

### ISSUE THREAD

**Issue by ezemania2** [DorielRivalet/mhfz-overlay#49]

**Comment by DorielRivalet** [comment]
Upload in what sense? There is no public leaderboard yet, it's all local. If you set the game folder and database file locations and enable quest logging, you should see the runs you do with the overlay in the Most Recent section.

**Comment by ezemania2** [comment]
yeah I'm using the 0.21.0
but what is exactly the database file location you mean the quest?

**Comment by DorielRivalet** [comment]
This is the way I personally do it:

1. Go to Mezeporta, load the Overlay.
2. Press `Shift+F1`, go to Quest Log tab.
3. Go to Settings tab inside the Quest Log tab, press Select Game Folder button
4. Navigate to the folder where your mhf.exe (the game) resides, select it and press Select folder.
5. press the Select Custom Folder for quest Runs Database.
6. Navigate to any folder (I made a database folder in the game folder), give the file a name (I named mine MHFZ_Overlay.sqlite), press Save.
7. Toggle Quest Logging
8. Press the green Save button at the bottom in order for the overlay settings to be saved.
9. Restart the Overlay.
10. Do a run and once you are back at hub, check if the run is there by going into Config -> Quest Log -> Section Most Recent

**Comment by ezemania2** [comment]
ok Thank for your help

**Comment by DorielRivalet** [comment]
Addendum for v0.22.0: https://github.com/DorielRivalet/mhfz-overlay/blob/main/FAQ.md#how-to-enable-quest-logging
