### ISSUE TITLE
[BUG] - Wrong icon

### ISSUE THREAD

**Issue by ezemania2** [DorielRivalet/mhfz-overlay#77]
### What happened?

![image](https://user-images.githubusercontent.com/81659486/231255706-28c2cfe8-ca09-4789-9a42-7f98ee989044.png)
I got the crimson fatalis's icon for keo's quest

### What version of the program are you using?

Latest version

### What version of the game are you using?

High-Grade Edition

**Comment by DorielRivalet** [comment]
What is the Quest ID for the Keo quest? You can check by going into Config -> Quest Log -> Settings and enabling Quest ID.
Also try toggling the override option found in General:
![image](https://user-images.githubusercontent.com/100863878/232265643-117c6ca0-8f91-4a97-a4d7-2cb14a65a401.png)
and see if it changes anything.

**Comment by ezemania2** [comment]
I'll did it when in a few day

**Comment by ezemania2** [comment]
it was the quest id 65000

**Comment by DorielRivalet** [comment]
Has this happened in any other quest? Also, did the override option enable/disable change the icon?

Any quest with the ID over 63421 is probably a custom quest, and as such the overlay might display incorrect data more often than not, compared to "official" quests. The original Keo quest I tested had ID 58043, as seen in the image. 
![image](https://user-images.githubusercontent.com/100863878/234737294-1353a064-a0f5-428c-af14-ae4718010f41.png)

**Comment by ezemania2** [comment]
Didn't saw it in other quests and yes it was a custom quest

**Comment by DorielRivalet** [comment]
Thanks for the bug report. I'm closing this and opening a new issue related to this. See #89.
